version: "3.9"

services:
  bot:
    container_name: bot
    image: yannxy/bot:1.0.0
    build: ./bot
    depends_on:
      - api

  api:
    container_name: api
    image: yannxy/bot-api:1.0.0
    build: ./api
    ports:
      - "4000:4000"
    environment:
      - DB_URL=${DB_URL}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
